//@Library('jenkins_shared@test') _
library 'jenkins_shared'
library 'utils-pipeline'
pipe.call(
    nombre: "Juan",
    apellido: "Guerra",
    edad: 32
)
script {
    def output = new helpers.Output()
    output.SaludoNombre("Juan")
}