pipeline {
    agent any

    stages {
        stage('Paso 1') {
            steps {
                echo "Hello World ${BUILD_NUMBER}"
            }
        }
        stage('Paso 2') {
            steps {
                echo 'Hello World ${BUILD_NUMBER}'
            }
        }
    }
}