pipeline {
    agent any

    stages {
        stage('Paso 1') {
            steps {
                echo "Hello World ${BUILD_NUMBER}"
                echo "con comillados bles se leen las variables"
            }
        }
        stage('Paso 2') {
            steps {
                echo 'Hello World ${BUILD_NUMBER}'
                echo 'con comillas simples no se reconoce la variable.. todo es texto'
            }
        }
    }
}